// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCe6UfbhNeVEBll6Wlt_VpMGWj-RT46X68',
    appId: '1:64513929376:web:5a6fa27c0a7fa3ee8399c5',
    messagingSenderId: '64513929376',
    projectId: 'parenting-assistant-app',
    authDomain: 'parenting-assistant-app.firebaseapp.com',
    storageBucket: 'parenting-assistant-app.firebasestorage.app',
    measurementId: 'G-29J0LMSCVP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCejs5I6hUMtJ2hl2ftUsEPc8HOwqpqD70',
    appId: '1:64513929376:android:c5aef59aa2cf78998399c5',
    messagingSenderId: '64513929376',
    projectId: 'parenting-assistant-app',
    storageBucket: 'parenting-assistant-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJVzBPyToODxjttaPcfkuOORbEGoezeGw',
    appId: '1:64513929376:ios:c6059972b001f0298399c5',
    messagingSenderId: '64513929376',
    projectId: 'parenting-assistant-app',
    storageBucket: 'parenting-assistant-app.firebasestorage.app',
    iosBundleId: 'com.example.parentingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJVzBPyToODxjttaPcfkuOORbEGoezeGw',
    appId: '1:64513929376:ios:c6059972b001f0298399c5',
    messagingSenderId: '64513929376',
    projectId: 'parenting-assistant-app',
    storageBucket: 'parenting-assistant-app.firebasestorage.app',
    iosBundleId: 'com.example.parentingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCe6UfbhNeVEBll6Wlt_VpMGWj-RT46X68',
    appId: '1:64513929376:web:0f129058f2bf81cf8399c5',
    messagingSenderId: '64513929376',
    projectId: 'parenting-assistant-app',
    authDomain: 'parenting-assistant-app.firebaseapp.com',
    storageBucket: 'parenting-assistant-app.firebasestorage.app',
    measurementId: 'G-QHHV3F8105',
  );
}
